### ISSUE TITLE
KUBERNETES_CONNECTION_TIMEOUT and KUBERNETES_REQUEST_TIMEOUT cannot be altered during runtime with quarkus

### ISSUE THREAD

**Issue by yayaythegreat** [strimzi/drain-cleaner#59]
Hello!

I am using Drain Cleaner 0.3.1

A bit of background, I am encountering intermittent issue with timeout(See error below)

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [patch]  for kind: [Pod]  with name: [kafka-cluster-zookeeper-2]  in namespace: [my-cluster]  failed.
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$3(HasMetadataOperation.java:244)
    ...
	at io.fabric8.kubernetes.client.dsl.Patchable.patch(Patchable.java:35)
	at io.strimzi.ValidatingWebhook.patchPod(ValidatingWebhook.java:136)
	at io.strimzi.ValidatingWebhook.annotatePodForRestart(ValidatingWebhook.java:121)
	at io.strimzi.ValidatingWebhook.webhook(ValidatingWebhook.java:88)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	... 17 more
Caused by: java.net.SocketTimeoutException: timeout
at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
	...
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	...
```

**I have tried extending the timeout time by declaring on command and/or using variable**(See below attempts):

**Using env var:**
```
spec:
    ...
    spec:
      containers:
        - name: strimzi-drain-cleaner
          image: quay.io/strimzi/drain-cleaner:0.3.1
          ...
          env:
          - name: QUARKUS_KUBERNETES_CLIENT_CONNECTION_TIMEOUT
            value: "PT3M"
          - name: QUARKUS_KUBERNETES_CLIENT_REQUEST_TIMEOUT
            value: "PT3M"
```

```
spec:
    ...
    spec:
      containers:
        - name: strimzi-drain-cleaner
          image: quay.io/strimzi/drain-cleaner:0.3.1
          ...
          env:
          - name: KUBERNETES_CONNECTION_TIMEOUT
            value: "100000"
          - name: KUBERNETES_WEBSOCKET_TIMEOUT
            value: "100000"
          - name: KUBERNETES_REQUEST_TIMEOUT
            value: "100000"
```

**Inserted additional parameter on command**
```
spec:
    ...
    spec:
      containers:
        - name: strimzi-drain-cleaner
          image: quay.io/strimzi/drain-cleaner:0.3.1
          command:
            - "/application"
            - "-Dquarkus.http.host=0.0.0.0"
            - "-Dquarkus.kubernetes-client.connection-timeout=PT2M"
            - "-Dquarkus.kubernetes-client.request-timeout=PT2M"
            - "--kafka"
            - "--zookeeper"
```

Unfortunately, kubernetes-client.connection/request-timeout is a build time property and cannot be changed at runtime with **[quarkus.io](https://quarkus.io/)**

<img width="1358" alt="Screen Shot 2022-10-04 at 7 28 08 PM" src="https://user-images.githubusercontent.com/52384198/193808317-bd5e0eaa-44ec-42c8-9cc9-1aa8f17b8d84.png">

```
2022-10-04 11:20:53,436 WARN  [io.qua.run.con.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.kubernetes-client.connection-timeout is set to 'PT2M' but it is build time fixed to 'PT10S'. Did you change the property quarkus.kubernetes-client.connection-timeout after building the application?
 - quarkus.kubernetes-client.request-timeout is set to 'PT2M' but it is build time fixed to 'PT10S'. Did you change the property quarkus.kubernetes-client.request-timeout after building the application?
```

Any other workaround I can look into is much appreciated.

Thanks!

**Comment by scholzj** [comment]
I think you will need to change it in the `application.properties` and build your own copy with these settings changed if you want to use it. You can possibly also try how it works in the `main` branch which does nto use native compilation anymore -> maybe you can change it more easily there.

**Comment by scholzj** [comment]
We do not use the native build anymore. So I think this should not work fine with 0.4.0.
