### ISSUE TITLE
Drain cleaner cannot start with read-only filesystem

### ISSUE THREAD

**Issue by MeijerM1** [strimzi/drain-cleaner#76]
Drain cleaner cannot start with read-only filesystem.

```
Feb 08, 2023 6:27:37 AM io.quarkus.vertx.core.runtime.VertxCoreRecorder
WARN: Unable to create Vert.x cache directory : %s
Feb 08, 2023 6:27:37 AM io.quarkus.vertx.core.runtime.VertxCoreRecorder
WARN: Unable to make the Vert.x cache directory (%s) world readable and writable
Feb 08, 2023 6:27:37 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.nio.file.FileSystemException: /tmp/vertx-cache: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:58)
	at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:31)
	at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67)
	at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:334)
	at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:274)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:242)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:610)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:592)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:286)
	at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)


```

Since the helm chart does not expose a way to  configure the pod definition this cannot be fixed.

**Comment by scholzj** [comment]
You can use the YAML files to install Drain Cleaner which you can edit in any way you want (there was no Helm Chart until the 0.4.0 release last week). It is reasonable to have this handled in the Helm Chart. But there is a simple workaround, so the `cannot be fixed` seems a bit harsh ;-).

**Comment by MeijerM1** [comment]
You're absolutely right, we're looking into using the YAML files, thanks!

What I meant was it cannot be fixed when using the Helm Chart :).

**Comment by MeijerM1** [comment]
We're looking into a production issue right now which we might be able to solve using the drain cleaner.

If we are able to fix it using the drain cleaner we might look into opening a PR to improve the Helm Chart ourselfs. No Guarantees though :)
